name: Building unity project
on:
 workflow_dispatch:
 
 push:
  branches:
   - "*"
   - "!master"
  paths:
   - "unity_env/**"
   
 pull_request:
  branches:
   - "*"
   - "!master"
  paths:
   - "unity_env/**"

jobs:
 Build-unity-project:
  runs-on: ubuntu-latest
 
  permissions:
   contents: write
  
  steps:

    - uses: actions/checkout@v4
      with:
       ref: ${{ github.head_ref }}
       fetch-depth: 0
       lfs: true

    - uses: actions/cache@v4
      with:
       path: unity_env/Library
       key: Library
       restore-keys: Library


    - name: Build
      uses: game-ci/unity-builder@v4.2.3
      env:
       UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
       UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
       UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
       unityVersion: auto
       targetPlatform: StandaloneLinux64
       projectPath: unity_env
       buildsPath: src/build
       buildName: vehiclePursuit

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
       name: Build-LinuxStandalone
       path: src/build

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
       commit_message: 'CI: Add build'
       file_pattern: 'src/build/*'
